In [11]:
import pandas as pd
import sqlite3
pd.options.display.max_columns = None

In [2]:
ss = pd.read_csv('state_stats.csv')
ud = pd.read_csv('ufo_data.csv', low_memory = False)
ma = pd.read_csv('merge_again.csv')

In [3]:
ss.head(3)

,name,drug_deaths,abbreviation,sightings,avg_sighting_duration,code,census_area
0,Alabama,724,al,691,1393.408828,1,50645.326
1,Alaska,107,ak,354,4231.830508,2,570640.950
2,Arizona,1725,az,2689,5949.009338,4,113594.084

In [4]:
ud.head(3)

,datetime,city,state,country,shape,duration,duration_hours,comments,date_posted,latitude,longitude,year,month
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8831,-97.9411,1949.0,10.0
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.3842,-98.5811,1949.0,10.0
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.9167,1955.0,10.0

In [5]:
ma

,year,death_rate,drug_deaths,state_codes,state_names,state_census_area,state_abb,state_sightings,duration,changing,...,obesityLow,obesityHigh,smokes,smokesLow,smokesHigh,-0.385218228,GEO_ID,NAME,population,B01003_001M
0,2014.0,15.2,723,1.0,Alabama,50645.326,al,691.0,1393.408828,13.0,...,32.1,35.0,21.1,19.8,22.5,NaN,0400000US01,Alabama,4849377,*****
1,2014.0,16.8,124,2.0,Alaska,570640.950,ak,354.0,4231.830508,5.0,...,27.8,31.6,19.9,18.2,21.6,NaN,0400000US02,Alaska,736732,*****
2,2014.0,12.6,356,4.0,Arizona,113594.084,az,2689.0,5949.009338,77.0,...,27.7,30.2,16.5,15.4,17.6,NaN,0400000US04,Arizona,6731484,*****
3,2014.0,18.2,"1,211",5.0,Arkansas,52035.477,ar,666.0,100867.138889,19.0,...,33.8,38.0,24.7,22.7,26.7,NaN,0400000US05,Arkansas,2966369,*****
4,2014.0,11.1,"4,521",6.0,California,155779.220,ca,9655.0,3928.781072,290.0,...,23.5,25.9,12.9,11.9,13.8,NaN,0400000US06,California,38802500,*****
5,2014.0,16.3,899,8.0,Colorado,103641.888,co,1505.0,3024.394751,38.0,...,20.4,22.2,15.7,14.8,16.6,NaN,0400000US08,Colorado,5355866,*****
6,2014.0,17.6,623,9.0,Connecticut,4842.355,ct,968.0,13089.214928,14.0,...,24.8,27.7,15.4,14.2,16.7,NaN,0400000US09,Connecticut,3596677,*****
7,2014.0,20.9,189,10.0,Delaware,1948.543,de,183.0,868.904372,4.0,...,28.6,32.7,19.9,17.9,21.8,NaN,0400000US10,Delaware,935614,*****
8,2014.0,13.2,"2,634",12.0,Florida,53624.759,fl,4200.0,13504.459262,113.0,...,25.0,27.5,17.7,16.5,18.8,NaN,0400000US12,Florida,19893297,*****
9,2014.0,11.9,"1,206",13.0,Georgia,57513.485,ga,1347.0,7968.701633,33.0,...,28.9,32.1,17.4,15.9,18.8,NaN,0400000US13,Georgia,10097343,*****
10,2014.0,10.9,157,15.0,Hawaii,6422.628,hi,353.0,19267.543909,7.0,...,20.7,23.5,14.1,13.0,15.3,NaN,0400000US15,Hawaii,1419561,*****
11,2014.0,13.7,212,16.0,Idaho,82643.117,id,554.0,968.556498,16.0,...,27.1,30.8,15.9,14.4,17.4,NaN,0400000US16,Idaho,1634464,*****
12,2014.0,13.1,"1,705",17.0,Illinois,55518.930,il,2645.0,877.362219,62.0,...,27.6,31.1,16.5,15.1,18.0,NaN,0400000US17,Illinois,12880580,*****
13,2014.0,18.2,"1,172",18.0,Indiana,35826.109,in,1386.0,3094.797763,25.0,...,31.5,33.9,22.9,21.8,24.1,NaN,0400000US18,Indiana,6596855,*****
14,2014.0,8.8,264,19.0,Iowa,55857.130,ia,707.0,949.626591,21.0,...,29.6,32.3,18.5,17.3,19.7,NaN,0400000US19,Iowa,3107126,*****
15,2014.0,11.7,332,20.0,Kansas,81758.717,ks,653.0,1514.714395,11.0,...,30.3,32.2,18.1,17.2,18.9,NaN,0400000US20,Kansas,2904021,*****
16,2014.0,24.7,"1,077",21.0,Kentucky,39486.338,ky,914.0,4205.386761,30.0,...,30.2,33.1,26.2,24.7,27.7,NaN,0400000US21,Kentucky,4413457,*****
17,2014.0,16.9,777,22.0,Louisiana,43203.905,la,598.0,11481.575251,16.0,...,33.4,36.4,24.0,22.6,25.4,NaN,0400000US22,Louisiana,4649676,*****
18,2014.0,16.8,216,23.0,Maine,30842.923,me,633.0,3066.431122,9.0,...,26.9,29.5,19.3,18.1,20.5,NaN,0400000US23,Maine,1330089,*****
19,2014.0,17.4,"1,070",24.0,Maryland,9707.241,md,911.0,833.780790,25.0,...,28.1,31.1,14.6,13.4,15.9,NaN,0400000US24,Maryland,5976407,*****
20,2014.0,19.0,"1,289",25.0,Massachusetts,7800.058,ma,1358.0,1312.187776,30.0,...,22.3,24.4,14.7,13.7,15.7,NaN,0400000US25,Massachusetts,6745408,*****
21,2014.0,18.0,"1,762",26.0,Michigan,56538.901,mi,2071.0,3885.088653,45.0,...,29.4,32.0,21.2,20.0,22.5,NaN,0400000US26,Michigan,9909877,*****
22,2014.0,9.6,517,27.0,Minnesota,79626.743,mn,1081.0,1411.120564,19.0,...,26.8,28.5,16.3,15.6,17.0,NaN,0400000US27,Minnesota,5457173,*****
23,2014.0,11.6,336,28.0,Mississippi,46923.274,ms,415.0,8784.190361,8.0,...,33.4,37.6,23.0,21.0,24.9,NaN,0400000US28,Mississippi,2994079,*****
24,2014.0,18.2,"1,067",29.0,Missouri,68741.522,mo,1576.0,1144.388198,34.0,...,28.6,31.9,20.6,19.2,22.1,NaN,0400000US29,Missouri,6063589,*****
25,2014.0,12.4,125,30.0,Montana,145545.801,mt,510.0,2148.723529,12.0,...,24.9,27.9,19.9,18.5,21.4,NaN,0400000US30,Montana,1023579,*****
26,2014.0,7.2,125,31.0,Nebraska,76824.171,ne,405.0,1063.565432,9.0,...,29.2,31.2,17.3,16.5,18.2,NaN,0400000US31,Nebraska,1881503,*****
27,2014.0,18.4,545,32.0,Nevada,109781.180,nv,905.0,2926.016519,23.0,...,25.3,30.1,17.0,15.0,19.0,NaN,0400000US32,Nevada,2839099,*****
28,2014.0,26.2,334,33.0,New Hampshire,8952.651,nh,535.0,2141.602804,16.0,...,25.8,29.1,17.5,16.0,19.0,NaN,0400000US33,New Hampshire,1326813,*****
29,2014.0,14.0,"1,253",34.0,New Jersey,7354.220,nj,1512.0,5299.992341,27.0,...,25.7,28.1,15.1,14.1,16.1,NaN,0400000US34,New Jersey,8938175,*****
30,2014.0,27.3,547,35.0,New Mexico,121298.148,nm,815.0,5185.816675,31.0,...,26.9,30.0,19.2,17.7,20.6,NaN,0400000US35,New Mexico,2085572,*****
31,2014.0,11.3,"2,300",36.0,New York,47126.399,ny,3219.0,2914.711572,73.0,...,25.6,28.4,14.4,13.3,15.5,NaN,0400000US36,New York,19746227,*****
32,2014.0,13.8,"1,358",37.0,North Carolina,48617.905,nc,1869.0,1281.831648,42.0,...,28.4,31.0,19.1,17.9,20.3,NaN,0400000US37,North Carolina,9943964,*****
33,2014.0,6.3,43,38.0,North Dakota,69000.798,nd,138.0,1105.405797,5.0,...,30.5,33.9,19.9,18.4,21.5,NaN,0400000US38,North Dakota,739482,*****
34,2014.0,24.6,"2,744",39.0,Ohio,40860.694,oh,2425.0,1576.187773,57.0,...,31.2,34.1,21.0,19.7,22.3,NaN,0400000US39,Ohio,11594163,*****
35,2014.0,20.3,777,40.0,Oklahoma,68594.921,ok,766.0,14929.384204,23.0,...,31.6,34.3,21.1,19.9,22.3,NaN,0400000US40,Oklahoma,3878051,*****
36,2014.0,12.8,522,41.0,Oregon,95988.013,or,1845.0,1064.210450,51.0,...,26.2,29.6,17.0,15.5,18.4,NaN,0400000US41,Oregon,3970239,*****
37,2014.0,21.9,"2,732",42.0,Pennsylvania,44742.703,pa,2582.0,3990.113091,43.0,...,28.9,31.4,19.9,18.8,21.1,NaN,0400000US42,Pennsylvania,12787209,*****
38,2014.0,23.4,247,44.0,Rhode Island,1033.814,ri,290.0,1811.881034,3.0,...,25.4,28.6,16.3,14.8,17.7,NaN,0400000US44,Rhode Island,1055173,*****
39,2014.0,14.4,701,45.0,South Carolina,30060.696,sc,1076.0,1102.498885,33.0,...,30.9,33.3,21.5,20.4,22.7,NaN,0400000US45,South Carolina,4832482,*****
40,2014.0,7.8,63,46.0,South Dakota,75811.000,sd,196.0,2608.640306,3.0,...,27.9,31.8,18.6,16.9,20.2,NaN,0400000US46,South Dakota,853175,*****
41,2014.0,19.5,"1,269",47.0,Tennessee,41234.896,tn,1193.0,1610.461526,25.0,...,29.3,33.1,24.2,22.3,26.1,NaN,0400000US47,Tennessee,6549352,*****
42,2014.0,9.7,"2,601",48.0,Texas,261231.711,tx,3677.0,2371.343283,100.0,...,30.6,33.3,14.5,13.6,15.5,NaN,0400000US48,Texas,26956958,*****
43,2014.0,22.4,603,49.0,Utah,82169.620,ut,743.0,4739.033647,22.0,...,24.9,26.6,9.7,9.0,10.3,NaN,0400000US49,Utah,2942902,*****
44,2014.0,13.9,83,50.0,Vermont,9216.657,vt,307.0,1077.587948,6.0,...,23.5,26.1,16.4,15.2,17.6,NaN,0400000US50,Vermont,626562,*****
45,2014.0,11.7,980,51.0,Virginia,39490.086,va,1393.0,9862.555276,35.0,...,27.2,29.7,19.5,18.4,20.7,NaN,0400000US51,Virginia,8326289,*****
46,2014.0,13.3,979,53.0,Washington,66455.521,wa,4268.0,13545.595628,92.0,...,26.0,28.5,15.3,14.3,16.4,NaN,0400000US53,Washington,7061530,*****
47,2014.0,35.5,627,54.0,West Virginia,24038.210,wv,486.0,6239.355967,11.0,...,34.2,37.2,26.7,25.2,28.1,NaN,0400000US54,West Virginia,1850326,*****
48,2014.0,15.1,853,55.0,Wisconsin,54157.805,wi,1333.0,2047.964966,23.0,...,29.6,32.8,17.4,16.0,18.7,NaN,0400000US55,Wisconsin,5757564,*****
49,2014.0,19.4,109,56.0,Wyoming,97093.141,wy,205.0,1841.629273,5.0,...,27.4,31.5,19.5,17.6,21.4,NaN,0400000US56,Wyoming,584153,*****
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0400000US11,District of Columbia,658893,*****
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0400000US72,Puerto Rico,3548397,*****

In [6]:
ma = ma.iloc[:,:-1]
ma

,year,death_rate,drug_deaths,state_codes,state_names,state_census_area,state_abb,state_sightings,duration,changing,...,obesity,obesityLow,obesityHigh,smokes,smokesLow,smokesHigh,-0.385218228,GEO_ID,NAME,population
0,2014.0,15.2,723,1.0,Alabama,50645.326,al,691.0,1393.408828,13.0,...,33.5,32.1,35.0,21.1,19.8,22.5,NaN,0400000US01,Alabama,4849377
1,2014.0,16.8,124,2.0,Alaska,570640.950,ak,354.0,4231.830508,5.0,...,29.7,27.8,31.6,19.9,18.2,21.6,NaN,0400000US02,Alaska,736732
2,2014.0,12.6,356,4.0,Arizona,113594.084,az,2689.0,5949.009338,77.0,...,28.9,27.7,30.2,16.5,15.4,17.6,NaN,0400000US04,Arizona,6731484
3,2014.0,18.2,"1,211",5.0,Arkansas,52035.477,ar,666.0,100867.138889,19.0,...,35.9,33.8,38.0,24.7,22.7,26.7,NaN,0400000US05,Arkansas,2966369
4,2014.0,11.1,"4,521",6.0,California,155779.220,ca,9655.0,3928.781072,290.0,...,24.7,23.5,25.9,12.9,11.9,13.8,NaN,0400000US06,California,38802500
5,2014.0,16.3,899,8.0,Colorado,103641.888,co,1505.0,3024.394751,38.0,...,21.3,20.4,22.2,15.7,14.8,16.6,NaN,0400000US08,Colorado,5355866
6,2014.0,17.6,623,9.0,Connecticut,4842.355,ct,968.0,13089.214928,14.0,...,26.3,24.8,27.7,15.4,14.2,16.7,NaN,0400000US09,Connecticut,3596677
7,2014.0,20.9,189,10.0,Delaware,1948.543,de,183.0,868.904372,4.0,...,30.7,28.6,32.7,19.9,17.9,21.8,NaN,0400000US10,Delaware,935614
8,2014.0,13.2,"2,634",12.0,Florida,53624.759,fl,4200.0,13504.459262,113.0,...,26.2,25.0,27.5,17.7,16.5,18.8,NaN,0400000US12,Florida,19893297
9,2014.0,11.9,"1,206",13.0,Georgia,57513.485,ga,1347.0,7968.701633,33.0,...,30.5,28.9,32.1,17.4,15.9,18.8,NaN,0400000US13,Georgia,10097343
10,2014.0,10.9,157,15.0,Hawaii,6422.628,hi,353.0,19267.543909,7.0,...,22.1,20.7,23.5,14.1,13.0,15.3,NaN,0400000US15,Hawaii,1419561
11,2014.0,13.7,212,16.0,Idaho,82643.117,id,554.0,968.556498,16.0,...,28.9,27.1,30.8,15.9,14.4,17.4,NaN,0400000US16,Idaho,1634464
12,2014.0,13.1,"1,705",17.0,Illinois,55518.930,il,2645.0,877.362219,62.0,...,29.3,27.6,31.1,16.5,15.1,18.0,NaN,0400000US17,Illinois,12880580
13,2014.0,18.2,"1,172",18.0,Indiana,35826.109,in,1386.0,3094.797763,25.0,...,32.7,31.5,33.9,22.9,21.8,24.1,NaN,0400000US18,Indiana,6596855
14,2014.0,8.8,264,19.0,Iowa,55857.130,ia,707.0,949.626591,21.0,...,30.9,29.6,32.3,18.5,17.3,19.7,NaN,0400000US19,Iowa,3107126
15,2014.0,11.7,332,20.0,Kansas,81758.717,ks,653.0,1514.714395,11.0,...,31.3,30.3,32.2,18.1,17.2,18.9,NaN,0400000US20,Kansas,2904021
16,2014.0,24.7,"1,077",21.0,Kentucky,39486.338,ky,914.0,4205.386761,30.0,...,31.6,30.2,33.1,26.2,24.7,27.7,NaN,0400000US21,Kentucky,4413457
17,2014.0,16.9,777,22.0,Louisiana,43203.905,la,598.0,11481.575251,16.0,...,34.9,33.4,36.4,24.0,22.6,25.4,NaN,0400000US22,Louisiana,4649676
18,2014.0,16.8,216,23.0,Maine,30842.923,me,633.0,3066.431122,9.0,...,28.2,26.9,29.5,19.3,18.1,20.5,NaN,0400000US23,Maine,1330089
19,2014.0,17.4,"1,070",24.0,Maryland,9707.241,md,911.0,833.780790,25.0,...,29.6,28.1,31.1,14.6,13.4,15.9,NaN,0400000US24,Maryland,5976407
20,2014.0,19.0,"1,289",25.0,Massachusetts,7800.058,ma,1358.0,1312.187776,30.0,...,23.3,22.3,24.4,14.7,13.7,15.7,NaN,0400000US25,Massachusetts,6745408
21,2014.0,18.0,"1,762",26.0,Michigan,56538.901,mi,2071.0,3885.088653,45.0,...,30.7,29.4,32.0,21.2,20.0,22.5,NaN,0400000US26,Michigan,9909877
22,2014.0,9.6,517,27.0,Minnesota,79626.743,mn,1081.0,1411.120564,19.0,...,27.6,26.8,28.5,16.3,15.6,17.0,NaN,0400000US27,Minnesota,5457173
23,2014.0,11.6,336,28.0,Mississippi,46923.274,ms,415.0,8784.190361,8.0,...,35.5,33.4,37.6,23.0,21.0,24.9,NaN,0400000US28,Mississippi,2994079
24,2014.0,18.2,"1,067",29.0,Missouri,68741.522,mo,1576.0,1144.388198,34.0,...,30.2,28.6,31.9,20.6,19.2,22.1,NaN,0400000US29,Missouri,6063589
25,2014.0,12.4,125,30.0,Montana,145545.801,mt,510.0,2148.723529,12.0,...,26.4,24.9,27.9,19.9,18.5,21.4,NaN,0400000US30,Montana,1023579
26,2014.0,7.2,125,31.0,Nebraska,76824.171,ne,405.0,1063.565432,9.0,...,30.2,29.2,31.2,17.3,16.5,18.2,NaN,0400000US31,Nebraska,1881503
27,2014.0,18.4,545,32.0,Nevada,109781.180,nv,905.0,2926.016519,23.0,...,27.7,25.3,30.1,17.0,15.0,19.0,NaN,0400000US32,Nevada,2839099
28,2014.0,26.2,334,33.0,New Hampshire,8952.651,nh,535.0,2141.602804,16.0,...,27.4,25.8,29.1,17.5,16.0,19.0,NaN,0400000US33,New Hampshire,1326813
29,2014.0,14.0,"1,253",34.0,New Jersey,7354.220,nj,1512.0,5299.992341,27.0,...,26.9,25.7,28.1,15.1,14.1,16.1,NaN,0400000US34,New Jersey,8938175
30,2014.0,27.3,547,35.0,New Mexico,121298.148,nm,815.0,5185.816675,31.0,...,28.4,26.9,30.0,19.2,17.7,20.6,NaN,0400000US35,New Mexico,2085572
31,2014.0,11.3,"2,300",36.0,New York,47126.399,ny,3219.0,2914.711572,73.0,...,27.0,25.6,28.4,14.4,13.3,15.5,NaN,0400000US36,New York,19746227
32,2014.0,13.8,"1,358",37.0,North Carolina,48617.905,nc,1869.0,1281.831648,42.0,...,29.7,28.4,31.0,19.1,17.9,20.3,NaN,0400000US37,North Carolina,9943964
33,2014.0,6.3,43,38.0,North Dakota,69000.798,nd,138.0,1105.405797,5.0,...,32.2,30.5,33.9,19.9,18.4,21.5,NaN,0400000US38,North Dakota,739482
34,2014.0,24.6,"2,744",39.0,Ohio,40860.694,oh,2425.0,1576.187773,57.0,...,32.6,31.2,34.1,21.0,19.7,22.3,NaN,0400000US39,Ohio,11594163
35,2014.0,20.3,777,40.0,Oklahoma,68594.921,ok,766.0,14929.384204,23.0,...,33.0,31.6,34.3,21.1,19.9,22.3,NaN,0400000US40,Oklahoma,3878051
36,2014.0,12.8,522,41.0,Oregon,95988.013,or,1845.0,1064.210450,51.0,...,27.9,26.2,29.6,17.0,15.5,18.4,NaN,0400000US41,Oregon,3970239
37,2014.0,21.9,"2,732",42.0,Pennsylvania,44742.703,pa,2582.0,3990.113091,43.0,...,30.2,28.9,31.4,19.9,18.8,21.1,NaN,0400000US42,Pennsylvania,12787209
38,2014.0,23.4,247,44.0,Rhode Island,1033.814,ri,290.0,1811.881034,3.0,...,27.0,25.4,28.6,16.3,14.8,17.7,NaN,0400000US44,Rhode Island,1055173
39,2014.0,14.4,701,45.0,South Carolina,30060.696,sc,1076.0,1102.498885,33.0,...,32.1,30.9,33.3,21.5,20.4,22.7,NaN,0400000US45,South Carolina,4832482
40,2014.0,7.8,63,46.0,South Dakota,75811.000,sd,196.0,2608.640306,3.0,...,29.8,27.9,31.8,18.6,16.9,20.2,NaN,0400000US46,South Dakota,853175
41,2014.0,19.5,"1,269",47.0,Tennessee,41234.896,tn,1193.0,1610.461526,25.0,...,31.2,29.3,33.1,24.2,22.3,26.1,NaN,0400000US47,Tennessee,6549352
42,2014.0,9.7,"2,601",48.0,Texas,261231.711,tx,3677.0,2371.343283,100.0,...,31.9,30.6,33.3,14.5,13.6,15.5,NaN,0400000US48,Texas,26956958
43,2014.0,22.4,603,49.0,Utah,82169.620,ut,743.0,4739.033647,22.0,...,25.7,24.9,26.6,9.7,9.0,10.3,NaN,0400000US49,Utah,2942902
44,2014.0,13.9,83,50.0,Vermont,9216.657,vt,307.0,1077.587948,6.0,...,24.8,23.5,26.1,16.4,15.2,17.6,NaN,0400000US50,Vermont,626562
45,2014.0,11.7,980,51.0,Virginia,39490.086,va,1393.0,9862.555276,35.0,...,28.5,27.2,29.7,19.5,18.4,20.7,NaN,0400000US51,Virginia,8326289
46,2014.0,13.3,979,53.0,Washington,66455.521,wa,4268.0,13545.595628,92.0,...,27.3,26.0,28.5,15.3,14.3,16.4,NaN,0400000US53,Washington,7061530
47,2014.0,35.5,627,54.0,West Virginia,24038.210,wv,486.0,6239.355967,11.0,...,35.7,34.2,37.2,26.7,25.2,28.1,NaN,0400000US54,West Virginia,1850326
48,2014.0,15.1,853,55.0,Wisconsin,54157.805,wi,1333.0,2047.964966,23.0,...,31.2,29.6,32.8,17.4,16.0,18.7,NaN,0400000US55,Wisconsin,5757564
49,2014.0,19.4,109,56.0,Wyoming,97093.141,wy,205.0,1841.629273,5.0,...,29.5,27.4,31.5,19.5,17.6,21.4,NaN,0400000US56,Wyoming,584153
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0400000US11,District of Columbia,658893
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0400000US72,Puerto Rico,3548397

In [7]:
ma.columns

Index(['year', 'death_rate', 'drug_deaths', 'state_codes', 'state_names',
       'state_census_area', 'state_abb', 'state_sightings', 'duration',
       'changing', 'chevron', 'cigar', 'circle', 'cone', 'cross', 'cylinder',
       'diamond', 'disk', 'egg', 'fireball', 'flash', 'formation', 'light',
       'other', 'oval', 'rectangle', 'sphere', 'teardrop', 'triangle',
       'unknown', 'id', 'state', 'abbr', 'poverty', 'povertyMoe', 'age',
       'ageMoe', 'income', 'incomeMoe', 'healthcare', 'healthcareLow',
       'healthcareHigh', 'obesity', 'obesityLow', 'obesityHigh', 'smokes',
       'smokesLow', 'smokesHigh', '-0.385218228', 'GEO_ID', 'NAME',
       'population'],
      dtype='object')

In [21]:
ma.drop(columns='-0.385218228', inplace=True)
ma2 = ma.dropna(inplace=False, axis=0)

In [29]:
ma2

,year,death_rate,drug_deaths,state_codes,state_names,state_census_area,state_abb,state_sightings,duration,changing,chevron,cigar,circle,cone,cross,cylinder,diamond,disk,egg,fireball,flash,formation,light,other,oval,rectangle,sphere,teardrop,triangle,unknown,id,state,abbr,poverty,povertyMoe,age,ageMoe,income,incomeMoe,healthcare,healthcareLow,healthcareHigh,obesity,obesityLow,obesityHigh,smokes,smokesLow,smokesHigh,GEO_ID,NAME,population
0,2014.0,15.2,723,1.0,Alabama,50645.326,al,691.0,1393.408828,13.0,9.0,16.0,64.0,1.0,3.0,12.0,15.0,44.0,12.0,47.0,15.0,14.0,139.0,44.0,34.0,10.0,50.0,6.0,83.0,46.0,1.0,Alabama,AL,19.3,0.5,38.6,0.2,42830.0,598.0,13.9,12.7,15.1,33.5,32.1,35.0,21.1,19.8,22.5,0400000US01,Alabama,4849377
2,2014.0,12.6,356,4.0,Arizona,113594.084,az,2689.0,5949.009338,77.0,32.0,54.0,239.0,14.0,7.0,42.0,31.0,135.0,25.0,182.0,43.0,125.0,613.0,220.0,116.0,39.0,177.0,25.0,254.0,176.0,4.0,Arizona,AZ,18.2,0.4,36.9,0.1,50068.0,483.0,14.4,13.3,15.6,28.9,27.7,30.2,16.5,15.4,17.6,0400000US04,Arizona,6731484
3,2014.0,18.2,"1,211",5.0,Arkansas,52035.477,ar,666.0,100867.138889,19.0,11.0,24.0,70.0,1.0,2.0,17.0,9.0,41.0,4.0,28.0,14.0,13.0,149.0,37.0,22.0,9.0,30.0,8.0,92.0,55.0,5.0,Arkansas,AR,18.9,0.5,37.8,0.2,41262.0,653.0,16.3,14.4,18.2,35.9,33.8,38.0,24.7,22.7,26.7,0400000US05,Arkansas,2966369
4,2014.0,11.1,"4,521",6.0,California,155779.220,ca,9655.0,3928.781072,290.0,158.0,216.0,899.0,31.0,32.0,134.0,155.0,693.0,95.0,744.0,154.0,318.0,1983.0,677.0,420.0,159.0,674.0,79.0,891.0,603.0,6.0,California,CA,16.4,0.2,36.0,0.1,61933.0,238.0,14.8,13.8,15.8,24.7,23.5,25.9,12.9,11.9,13.8,0400000US06,California,38802500
5,2014.0,16.3,899,8.0,Colorado,103641.888,co,1505.0,3024.394751,38.0,32.0,35.0,123.0,3.0,3.0,31.0,15.0,99.0,12.0,99.0,37.0,45.0,308.0,115.0,72.0,26.0,110.0,12.0,172.0,89.0,8.0,Colorado,CO,12.0,0.4,36.3,0.1,61303.0,487.0,12.8,11.9,13.6,21.3,20.4,22.2,15.7,14.8,16.6,0400000US08,Colorado,5355866
6,2014.0,17.6,623,9.0,Connecticut,4842.355,ct,968.0,13089.214928,14.0,13.0,34.0,101.0,5.0,5.0,20.0,16.0,61.0,8.0,97.0,14.0,18.0,172.0,66.0,49.0,23.0,50.0,14.0,86.0,73.0,9.0,Connecticut,CT,10.8,0.5,40.5,0.2,70048.0,828.0,8.7,7.6,9.7,26.3,24.8,27.7,15.4,14.2,16.7,0400000US09,Connecticut,3596677
8,2014.0,13.2,"2,634",12.0,Florida,53624.759,fl,4200.0,13504.459262,113.0,51.0,89.0,387.0,13.0,13.0,72.0,56.0,242.0,37.0,452.0,66.0,126.0,821.0,280.0,214.0,69.0,292.0,38.0,385.0,293.0,12.0,Florida,FL,16.5,0.3,41.6,0.1,47463.0,329.0,17.6,16.4,18.8,26.2,25.0,27.5,17.7,16.5,18.8,0400000US12,Florida,19893297
9,2014.0,11.9,"1,206",13.0,Georgia,57513.485,ga,1347.0,7968.701633,33.0,10.0,40.0,148.0,5.0,5.0,17.0,20.0,90.0,16.0,104.0,22.0,26.0,263.0,110.0,60.0,25.0,89.0,14.0,134.0,94.0,13.0,Georgia,GA,18.3,0.4,36.1,0.1,49321.0,543.0,20.9,19.3,22.5,30.5,28.9,32.1,17.4,15.9,18.8,0400000US13,Georgia,10097343
11,2014.0,13.7,212,16.0,Idaho,82643.117,id,554.0,968.556498,16.0,8.0,17.0,49.0,2.0,3.0,4.0,5.0,43.0,3.0,36.0,12.0,16.0,139.0,36.0,17.0,8.0,34.0,4.0,54.0,33.0,16.0,Idaho,ID,14.8,0.7,35.9,0.2,47861.0,1275.0,16.5,15.0,18.1,28.9,27.1,30.8,15.9,14.4,17.4,0400000US16,Idaho,1634464
12,2014.0,13.1,"1,705",17.0,Illinois,55518.930,il,2645.0,877.362219,62.0,29.0,59.0,279.0,7.0,5.0,35.0,29.0,159.0,30.0,217.0,39.0,96.0,560.0,160.0,119.0,41.0,155.0,21.0,316.0,170.0,17.0,Illinois,IL,14.4,0.3,37.5,0.2,57444.0,429.0,11.9,10.5,13.3,29.3,27.6,31.1,16.5,15.1,18.0,0400000US17,Illinois,12880580
13,2014.0,18.2,"1,172",18.0,Indiana,35826.109,in,1386.0,3094.797763,25.0,11.0,32.0,129.0,5.0,1.0,23.0,20.0,92.0,11.0,127.0,22.0,39.0,283.0,98.0,62.0,23.0,95.0,9.0,155.0,102.0,18.0,Indiana,IN,15.2,0.4,37.4,0.2,49446.0,487.0,14.8,13.8,15.8,32.7,31.5,33.9,22.9,21.8,24.1,0400000US18,Indiana,6596855
15,2014.0,11.7,332,20.0,Kansas,81758.717,ks,653.0,1514.714395,11.0,4.0,19.0,53.0,3.0,8.0,12.0,8.0,32.0,9.0,51.0,12.0,19.0,146.0,53.0,18.0,8.0,44.0,10.0,69.0,49.0,20.0,Kansas,KS,13.6,0.5,36.2,0.1,52504.0,706.0,14.5,13.7,15.3,31.3,30.3,32.2,18.1,17.2,18.9,0400000US20,Kansas,2904021
16,2014.0,24.7,"1,077",21.0,Kentucky,39486.338,ky,914.0,4205.386761,30.0,10.0,34.0,92.0,2.0,3.0,11.0,14.0,68.0,6.0,70.0,9.0,15.0,179.0,68.0,35.0,19.0,54.0,4.0,110.0,68.0,21.0,Kentucky,KY,19.1,0.5,38.5,0.2,42958.0,697.0,10.0,8.8,11.1,31.6,30.2,33.1,26.2,24.7,27.7,0400000US21,Kentucky,4413457
20,2014.0,19.0,"1,289",25.0,Massachusetts,7800.058,ma,1358.0,1312.187776,30.0,16.0,31.0,127.0,6.0,2.0,24.0,25.0,89.0,14.0,97.0,20.0,33.0,255.0,103.0,86.0,24.0,100.0,13.0,139.0,104.0,25.0,Massachusetts,MA,11.6,0.3,39.4,0.2,69160.0,957.0,4.6,4.0,5.2,23.3,22.3,24.4,14.7,13.7,15.7,0400000US25,Massachusetts,6745408
21,2014.0,18.0,"1,762",26.0,Michigan,56538.901,mi,2071.0,3885.088653,45.0,11.0,47.0,170.0,10.0,4.0,28.0,32.0,149.0,17.0,188.0,28.0,64.0,427.0,130.0,96.0,39.0,132.0,19.0,239.0,137.0,26.0,Michigan,MI,16.2,0.3,39.6,0.1,49847.0,385.0,10.3,9.3,11.2,30.7,29.4,32.0,21.2,20.0,22.5,0400000US26,Michigan,9909877
22,2014.0,9.6,517,27.0,Minnesota,79626.743,mn,1081.0,1411.120564,19.0,19.0,26.0,99.0,1.0,4.0,10.0,17.0,62.0,10.0,64.0,20.0,50.0,231.0,71.0,46.0,24.0,70.0,12.0,132.0,76.0,27.0,Minnesota,MN,11.5,0.4,37.8,0.1,61481.0,471.0,7.3,6.7,7.9,27.6,26.8,28.5,16.3,15.6,17.0,0400000US27,Minnesota,5457173
23,2014.0,11.6,336,28.0,Mississippi,46923.274,ms,415.0,8784.190361,8.0,4.0,11.0,45.0,1.0,1.0,12.0,4.0,36.0,5.0,24.0,9.0,6.0,75.0,32.0,17.0,7.0,24.0,4.0,51.0,31.0,28.0,Mississippi,MS,21.5,0.6,36.7,0.2,39680.0,773.0,18.8,17.0,20.7,35.5,33.4,37.6,23.0,21.0,24.9,0400000US28,Mississippi,2994079
24,2014.0,18.2,"1,067",29.0,Missouri,68741.522,mo,1576.0,1144.388198,34.0,28.0,56.0,110.0,5.0,4.0,37.0,23.0,102.0,9.0,132.0,15.0,26.0,328.0,116.0,61.0,23.0,113.0,14.0,192.0,118.0,29.0,Missouri,MO,15.5,0.4,38.5,0.1,48363.0,567.0,12.9,11.6,14.3,30.2,28.6,31.9,20.6,19.2,22.1,0400000US29,Missouri,6063589
25,2014.0,12.4,125,30.0,Montana,145545.801,mt,510.0,2148.723529,12.0,8.0,11.0,33.0,1.0,2.0,3.0,10.0,32.0,4.0,57.0,11.0,15.0,115.0,27.0,28.0,5.0,28.0,3.0,38.0,49.0,30.0,Montana,MT,15.4,0.8,39.6,0.3,46328.0,1217.0,12.9,11.6,14.1,26.4,24.9,27.9,19.9,18.5,21.4,0400000US30,Montana,1023579
26,2014.0,7.2,125,31.0,Nebraska,76824.171,ne,405.0,1063.565432,9.0,3.0,15.0,36.0,2.0,1.0,4.0,7.0,21.0,3.0,27.0,4.0,9.0,87.0,33.0,15.0,13.0,33.0,7.0,36.0,31.0,31.0,Nebraska,NE,12.4,0.5,36.2,0.2,52686.0,688.0,12.4,11.5,13.2,30.2,29.2,31.2,17.3,16.5,18.2,0400000US31,Nebraska,1881503
27,2014.0,18.4,545,32.0,Nevada,109781.180,nv,905.0,2926.016519,23.0,15.0,25.0,73.0,3.0,1.0,18.0,10.0,56.0,5.0,51.0,15.0,38.0,183.0,78.0,55.0,13.0,65.0,9.0,65.0,75.0,32.0,Nevada,NV,15.2,0.7,37.4,0.2,51450.0,683.0,17.1,15.0,19.3,27.7,25.3,30.1,17.0,15.0,19.0,0400000US32,Nevada,2839099
29,2014.0,14.0,"1,253",34.0,New Jersey,7354.220,nj,1512.0,5299.992341,27.0,16.0,37.0,151.0,8.0,4.0,23.0,21.0,140.0,11.0,126.0,27.0,39.0,274.0,120.0,83.0,28.0,99.0,13.0,136.0,104.0,34.0,New Jersey,NJ,11.1,0.3,39.4,0.2,71919.0,438.0,12.5,11.5,13.4,26.9,25.7,28.1,15.1,14.1,16.1,0400000US34,New Jersey,8938175
30,2014.0,27.3,547,35.0,New Mexico,121298.148,nm,815.0,5185.816675,31.0,11.0,18.0,62.0,13.0,3.0,18.0,15.0,56.0,7.0,44.0,19.0,19.0,171.0,56.0,34.0,20.0,49.0,11.0,56.0,72.0,35.0,New Mexico,NM,21.3,0.9,37.2,0.2,44803.0,849.0,15.4,14.1,16.8,28.4,26.9,30.0,19.2,17.7,20.6,0400000US35,New Mexico,2085572
31,2014.0,11.3,"2,300",36.0,New York,47126.399,ny,3219.0,2914.711572,73.0,47.0,91.0,331.0,10.0,11.0,44.0,51.0,239.0,42.0,240.0,59.0,93.0,622.0,215.0,177.0,53.0,191.0,36.0,314.0,211.0,36.0,New York,NY,15.9,0.3,38.2,0.1,58878.0,393.0,12.3,11.1,13.4,27.0,25.6,28.4,14.4,13.3,15.5,0400000US36,New York,19746227
32,2014.0,13.8,"1,358",37.0,North Carolina,48617.905,nc,1869.0,1281.831648,42.0,28.0,50.0,192.0,8.0,6.0,30.0,25.0,117.0,15.0,135.0,29.0,63.0,392.0,117.0,80.0,32.0,136.0,16.0,192.0,143.0,37.0,North Carolina,NC,17.2,0.3,38.3,0.1,46556.0,381.0,16.1,15.1,17.2,29.7,28.4,31.0,19.1,17.9,20.3,0400000US37,North Carolina,9943964
34,2014.0,24.6,"2,744",39.0,Ohio,40860.694,oh,2425.0,1576.187773,57.0,18.0,61.0,230.0,13.0,9.0,42.0,40.0,157.0,23.0,238.0,30.0,75.0,472.0,150.0,114.0,35.0,190.0,21.0,267.0,157.0,39.0,Ohio,OH,15.8,0.3,39.4,0.1,49308.0,363.0,10.2,9.2,11.3,32.6,31.2,34.1,21.0,19.7,22.3,0400000US39,Ohio,11594163
35,2014.0,20.3,777,40.0,Oklahoma,68594.921,ok,766.0,14929.384204,23.0,8.0,30.0,71.0,6.0,4.0,15.0,8.0,48.0,3.0,54.0,13.0,25.0,157.0,56.0,32.0,17.0,38.0,7.0,71.0,70.0,40.0,Oklahoma,OK,16.6,0.4,36.2,0.2,47529.0,454.0,13.9,12.9,15.0,33.0,31.6,34.3,21.1,19.9,22.3,0400000US40,Oklahoma,3878051
36,2014.0,12.8,522,41.0,Oregon,95988.013,or,1845.0,1064.210450,51.0,22.0,50.0,178.0,5.0,8.0,36.0,24.0,86.0,13.0,128.0,33.0,51.0,421.0,124.0,78.0,22.0,137.0,15.0,155.0,125.0,41.0,Oregon,OR,16.6,0.5,39.3,0.2,51075.0,490.0,11.0,9.7,12.4,27.9,26.2,29.6,17.0,15.5,18.4,0400000US41,Oregon,3970239
37,2014.0,21.9,"2,732",42.0,Pennsylvania,44742.703,pa,2582.0,3990.113091,43.0,17.0,79.0,247.0,16.0,7.0,34.0,36.0,175.0,26.0,234.0,31.0,90.0,514.0,178.0,134.0,42.0,154.0,25.0,250.0,190.0,42.0,Pennsylvania,PA,13.6,0.3,40.7,0.1,53234.0,420.0,10.1,9.2,11.1,30.2,28.9,31.4,19.9,18.8,21.1,0400000US42,Pennsylvania,12787209
39,2014.0,14.4,701,45.0,South Carolina,30060.696,sc,1076.0,1102.498885,33.0,9.0,28.0,114.0,4.0,2.0,13.0,10.0,50.0,3.0,87.0,23.0,41.0,268.0,68.0,43.0,13.0,72.0,8.0,95.0,74.0,45.0,South Carolina,SC,18.0,0.5,38.8,0.1,45238.0,507.0,17.1,16.0,18.2,32.1,30.9,33.3,21.5,20.4,22.7,0400000US45,South Carolina,4832482
41,2014.0,19.5,"1,269",47.0,Tennessee,41234.896,tn,1193.0,1610.461526,25.0,15.0,44.0,110.0,4.0,3.0,42.0,20.0,76.0,12.0,88.0,15.0,30.0,207.0,86.0,63.0,20.0,81.0,8.0,129.0,84.0,47.0,Tennessee,TN,18.3,0.4,38.6,0.1,44361.0,561.0,14.2,12.6,15.9,31.2,29.3,33.1,24.2,22.3,26.1,0400000US47,Tennessee,6549352
42,2014.0,9.7,"2,601",48.0,Texas,261231.711,tx,3677.0,2371.343283,100.0,55.0,113.0,306.0,11.0,8.0,65.0,58.0,238.0,35.0,215.0,59.0,110.0,745.0,303.0,205.0,72.0,221.0,38.0,382.0,284.0,48.0,Texas,TX,17.2,0.2,34.3,0.1,53035.0,377.0,24.9,23.7,26.1,31.9,30.6,33.3,14.5,13.6,15.5,0400000US48,Texas,26956958
43,2014.0,22.4,603,49.0,Utah,82169.620,ut,743.0,4739.033647,22.0,10.0,12.0,69.0,4.0,2.0,6.0,12.0,58.0,9.0,61.0,15.0,25.0,152.0,46.0,26.0,9.0,55.0,9.0,80.0,49.0,49.0,Utah,UT,11.7,0.6,30.5,0.1,60922.0,658.0,13.9,13.2,14.6,25.7,24.9,26.6,9.7,9.0,10.3,0400000US49,Utah,2942902
44,2014.0,13.9,83,50.0,Vermont,9216.657,vt,307.0,1077.587948,6.0,2.0,7.0,27.0,3.0,3.0,7.0,2.0,15.0,1.0,26.0,7.0,12.0,66.0,20.0,14.0,5.0,26.0,2.0,27.0,23.0,50.0,Vermont,VT,12.2,0.8,42.8,0.3,54166.0,1724.0,6.7,5.9,7.5,24.8,23.5,26.1,16.4,15.2,17.6,0400000US50,Vermont,626562
45,2014.0,11.7,980,51.0,Virginia,39490.086,va,1393.0,9862.555276,35.0,20.0,46.0,144.0,7.0,4.0,20.0,23.0,91.0,12.0,96.0,26.0,38.0,253.0,90.0,64.0,19.0,109.0,10.0,140.0,117.0,51.0,Virginia,VA,11.8,0.3,37.7,0.1,64902.0,624.0,13.1,12.0,14.1,28.5,27.2,29.7,19.5,18.4,20.7,0400000US51,Virginia,8326289
46,2014.0,13.3,979,53.0,Washington,66455.521,wa,4268.0,13545.595628,92.0,46.0,66.0,347.0,17.0,8.0,56.0,53.0,210.0,38.0,381.0,82.0,127.0,935.0,283.0,189.0,65.0,289.0,29.0,358.0,318.0,53.0,Washington,WA,13.2,0.4,37.5,0.1,61366.0,485.0,10.7,9.7,11.8,27.3,26.0,28.5,15.3,14.3,16.4,0400000US53,Washington,7061530
47,2014.0,35.5,627,54.0,West Virginia,24038.210,wv,486.0,6239.355967,11.0,5.0,13.0,49.0,1.0,2.0,18.0,3.0,29.0,6.0,29.0,4.0,14.0,104.0,31.0,25.0,5.0,23.0,4.0,58.0,42.0,54.0,West Virginia,WV,18.3,0.7,41.9,0.2,41059.0,651.0,10.1,9.1,11.2,35.7,34.2,37.2,26.7,25.2,28.1,0400000US54,West Virginia,1850326
48,2014.0,15.1,853,55.0,Wisconsin,54157.805,wi,1333.0,2047.964966,23.0,8.0,34.0,135.0,4.0,4.0,18.0,26.0,73.0,11.0,127.0,18.0,64.0,297.0,83.0,45.0,15.0,80.0,14.0,120.0,105.0,55.0,Wisconsin,WI,13.2,0.4,39.2,0.2,52622.0,433.0,8.5,7.4,9.7,31.2,29.6,32.8,17.4,16.0,18.7,0400000US55,Wisconsin,5757564

In [31]:
ma2.columns

Index(['year', 'death_rate', 'drug_deaths', 'state_codes', 'state_names',
       'state_census_area', 'state_abb', 'state_sightings', 'duration',
       'changing', 'chevron', 'cigar', 'circle', 'cone', 'cross', 'cylinder',
       'diamond', 'disk', 'egg', 'fireball', 'flash', 'formation', 'light',
       'other', 'oval', 'rectangle', 'sphere', 'teardrop', 'triangle',
       'unknown', 'id', 'state', 'abbr', 'poverty', 'povertyMoe', 'age',
       'ageMoe', 'income', 'incomeMoe', 'healthcare', 'healthcareLow',
       'healthcareHigh', 'obesity', 'obesityLow', 'obesityHigh', 'smokes',
       'smokesLow', 'smokesHigh', 'GEO_ID', 'NAME', 'population'],
      dtype='object')

In [34]:
ma2.dtypes

year                 float64
death_rate           float64
drug_deaths           object
state_codes          float64
state_names           object
state_census_area    float64
state_abb             object
state_sightings      float64
duration             float64
changing             float64
chevron              float64
cigar                float64
circle               float64
cone                 float64
cross                float64
cylinder             float64
diamond              float64
disk                 float64
egg                  float64
fireball             float64
flash                float64
formation            float64
light                float64
other                float64
oval                 float64
rectangle            float64
sphere               float64
teardrop             float64
triangle             float64
unknown              float64
id                   float64
state                 object
abbr                  object
poverty              float64
povertyMoe           float64
age                  float64
ageMoe               float64
income               float64
incomeMoe            float64
healthcare           float64
healthcareLow        float64
healthcareHigh       float64
obesity              float64
obesityLow           float64
obesityHigh          float64
smokes               float64
smokesLow            float64
smokesHigh           float64
GEO_ID                object
NAME                  object
population             int64
dtype: object

In [23]:
ud.dropna(inplace=True)
ud

,datetime,city,state,country,shape,duration,duration_hours,comments,date_posted,latitude,longitude,year,month
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8831,-97.9411,1949.0,10.0
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783,-96.6458,1956.0,10.0
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4181,-157.8036,1960.0,10.0
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595,-82.1889,1961.0,10.0
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175,-73.4083,1965.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80327,9/9/2013 21:15,nashville,tn,us,light,600,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.1658,-86.7844,2013.0,9.0
80328,9/9/2013 22:00,boise,id,us,circle,1200,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.6136,-116.2025,2013.0,9.0
80329,9/9/2013 22:00,napa,ca,us,other,1200,hour,Napa UFO&#44,9/30/2013,38.2972,-122.2844,2013.0,9.0
80330,9/9/2013 22:20,vienna,va,us,circle,5,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.9011,-77.2656,2013.0,9.0
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.6528,-97.4778,2013.0,9.0

In [24]:
db_conn = sqlite3.connect('../database.sqlite')

In [25]:
c = db_conn.cursor()

In [26]:
c.execute('DROP TABLE IF EXISTS ufo_data;')

c.execute(
    
"""
CREATE TABLE ufo_data(
id SERIAL PRIMARY KEY,
datetime VARCHAR,
city VARCHAR,
state VARCHAR,
country VARCHAR,
shape VARCHAR,
duration FLOAT,
duration_hours VARCHAR,
comments VARCHAR,
date_posted VARCHAR,
latitude FLOAT,
longitude FLOAT,
year FLOAT,
month FLOAT,
Foreign Key (state) REFERENCES state_stats(abbreviation));

"""
    
)

In [28]:
c.execute('DROP TABLE IF EXISTS state_stats;')

c.execute(
    
"""

CREATE TABLE state_stats(
name VARCHAR,
drug_deaths INT,
abbreviation VARCHAR,
sightings INT,
avg_sighting_duration FLOAT,
code VARCHAR,
census_area FLOAT,
PRIMARY KEY (abbreviation));

"""
    
)

In [42]:
c.execute('DROP TABLE IF EXISTS merge_again;')

c.execute(
    
"""
CREATE TABLE merge_again(
year FLOAT,
death_rate FLOAT,
drug_deaths VARCHAR,
state_codes FLOAT,
state_names VARCHAR,
state_census_area FLOAT,
state_abb VARCHAR,
state_sightings FLOAT,
duration FLOAT,
changing FLOAT,
chevron FLOAT,
cigar FLOAT,
circle FLOAT,
cone FLOAT,
cross FLOAT,
cylinder FLOAT,
diamond FLOAT,
disk FLOAT,
egg FLOAT,
fireball FLOAT,
flash FLOAT,
formation FLOAT,
light FLOAT,
other FLOAT,
oval FLOAT,
rectangle FLOAT,
sphere FLOAT,
teardrop FLOAT,
triangle FLOAT,
unknown FLOAT,
id INT PRIMARY KEY,
state VARCHAR,
abbr VARCHAR,
poverty FLOAT,
povertyMoe FLOAT,
age FLOAT,
ageMoe FLOAT,
income FLOAT,
incomeMoe FLOAT,
healthcare FLOAT,
healthcareLow FLOAT,
healthcareHigh FLOAT,
obesity FLOAT,
obesityLow FLOAT,
obesityHigh FLOAT,
smokes FLOAT,
smokesLow FLOAT,
smokesHigh FLOAT,
GEO_ID VARCHAR,
NAME VARCHAR,
population INT);

"""
)

In [43]:
ud.to_sql('ufo_data', db_conn, if_exists='append', index=False)
ss.to_sql('state_stats', db_conn, if_exists='append', index=False)
ma2.to_sql('merge_again', db_conn, if_exists='append', index=False)

In [44]:
# Test 1 with Pandas

pd.read_sql("SELECT * FROM ufo_data LIMIT 3", db_conn)

,id,datetime,city,state,country,shape,duration,duration_hours,comments,date_posted,latitude,longitude,year,month
0,None,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8831,-97.9411,1949.0,10.0
1,None,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783,-96.6458,1956.0,10.0
2,None,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4181,-157.8036,1960.0,10.0

In [45]:
# Test 2 with Pandas

pd.read_sql("SELECT * FROM state_stats LIMIT 3", db_conn)

,name,drug_deaths,abbreviation,sightings,avg_sighting_duration,code,census_area
0,Alabama,724,al,691,1393.408828,1,50645.326
1,Alaska,107,ak,354,4231.830508,2,570640.950
2,Arizona,1725,az,2689,5949.009338,4,113594.084

In [46]:
# Test 3 with Pandas

pd.read_sql("SELECT * FROM merge_again LIMIT 3", db_conn)

,year,death_rate,drug_deaths,state_codes,state_names,state_census_area,state_abb,state_sightings,duration,changing,chevron,cigar,circle,cone,cross,cylinder,diamond,disk,egg,fireball,flash,formation,light,other,oval,rectangle,sphere,teardrop,triangle,unknown,id,state,abbr,poverty,povertyMoe,age,ageMoe,income,incomeMoe,healthcare,healthcareLow,healthcareHigh,obesity,obesityLow,obesityHigh,smokes,smokesLow,smokesHigh,GEO_ID,NAME,population
0,2014.0,15.2,723,1.0,Alabama,50645.326,al,691.0,1393.408828,13.0,9.0,16.0,64.0,1.0,3.0,12.0,15.0,44.0,12.0,47.0,15.0,14.0,139.0,44.0,34.0,10.0,50.0,6.0,83.0,46.0,1,Alabama,AL,19.3,0.5,38.6,0.2,42830.0,598.0,13.9,12.7,15.1,33.5,32.1,35.0,21.1,19.8,22.5,0400000US01,Alabama,4849377
1,2014.0,12.6,356,4.0,Arizona,113594.084,az,2689.0,5949.009338,77.0,32.0,54.0,239.0,14.0,7.0,42.0,31.0,135.0,25.0,182.0,43.0,125.0,613.0,220.0,116.0,39.0,177.0,25.0,254.0,176.0,4,Arizona,AZ,18.2,0.4,36.9,0.1,50068.0,483.0,14.4,13.3,15.6,28.9,27.7,30.2,16.5,15.4,17.6,0400000US04,Arizona,6731484
2,2014.0,18.2,"1,211",5.0,Arkansas,52035.477,ar,666.0,100867.138889,19.0,11.0,24.0,70.0,1.0,2.0,17.0,9.0,41.0,4.0,28.0,14.0,13.0,149.0,37.0,22.0,9.0,30.0,8.0,92.0,55.0,5,Arkansas,AR,18.9,0.5,37.8,0.2,41262.0,653.0,16.3,14.4,18.2,35.9,33.8,38.0,24.7,22.7,26.7,0400000US05,Arkansas,2966369

In [47]:
# Test with SQLAlchemy

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from scipy.stats import ttest_ind

In [48]:
engine = create_engine("sqlite:///../database.sqlite")

In [49]:
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

In [50]:
# We can view all of the classes that automap found
Base.classes.keys()

['merge_again', 'state_stats', 'ufo_data']

In [58]:
ufo_data = Base.classes.ufo_data
state_stats = Base.classes.state_stats
merge_again = Base.classes.merge_again

In [59]:
session = Session(engine)

In [60]:
sightings = session.query(state_stats.sightings)

In [61]:
for s in sightings[:10]:
    print(s)

(691,)
(354,)
(2689,)
(666,)
(9655,)
(1505,)
(968,)
(183,)
(99,)
(4200,)

In [62]:
drugs_data = session.query(state_stats.name, state_stats.drug_deaths).all()

In [63]:
for state in drugs_data:
    print(state)

('Alabama', 724)
('Alaska', 107)
('Arizona', 1725)
('Arkansas', 439)
('California', 5515)
('Colorado', 992)
('Connecticut', 1087)
('Delaware', 403)
('District of Columbia', 300)
('Florida', 4921)
('Georgia', 1384)
('Hawaii', 223)
('Idaho', 249)
('Illinois', 2687)
('Indiana', 1591)
('Iowa', 278)
('Kansas', 348)
('Kentucky', 1339)
('Louisiana', 1162)
('Maine', 324)
('Maryland', 2392)
('Massachusetts', 2212)
('Michigan', 2513)
('Minnesota', 665)
('Mississippi', 288)
('Missouri', 1664)
('Montana', 120)
('Nebraska', 147)
('Nevada', 752)
('New Hampshire', 446)
('New Jersey', 2819)
('New Mexico', 513)
('New York', 2144)
('North Carolina', 2225)
('North Dakota', 63)
('Ohio', 4036)
('Oklahoma', 675)
('Oregon', 547)
('Pennsylvania', 4403)
('Rhode Island', 344)
('South Carolina', 1116)
('South Dakota', 56)
('Tennessee', 1881)
('Texas', 2968)
('Utah', 634)
('Vermont', 147)
('Virginia', 1464)
('Washington', 1181)
('West Virginia', 887)
('Wisconsin', 1081)
('Wyoming', 60)

In [65]:
whatever = session.query(merge_again.death_rate)

In [66]:
for death in whatever:
    print(death)

(15.2,)
(12.6,)
(18.2,)
(11.1,)
(16.3,)
(17.6,)
(13.2,)
(11.9,)
(13.7,)
(13.1,)
(18.2,)
(11.7,)
(24.7,)
(19.0,)
(18.0,)
(9.6,)
(11.6,)
(18.2,)
(12.4,)
(7.2,)
(18.4,)
(14.0,)
(27.3,)
(11.3,)
(13.8,)
(24.6,)
(20.3,)
(12.8,)
(21.9,)
(14.4,)
(19.5,)
(9.7,)
(22.4,)
(13.9,)
(11.7,)
(13.3,)
(35.5,)
(15.1,)